config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /pt|en/ do
    devise_for :users

    get 'states/:country' => 'admin#states'
    get 'cities/:country/:state' => 'admin#cities'
    get 'listapedidos' => 'orders#all_orders', :as => :all_orders

    resources :customers do
      patch 'generate_link'
    end
    resources :costs
    resources :orders do
      member do
        patch '/confirm_sale' => 'orders#confirm_sale', as: :confirm_sale
        patch '/reject_sale' => 'orders#reject_sale', as: :reject_sale
      end
    end
    resources :sales, only: %w(index show destroy) do
      member do
        post '/generate_boletos' => 'sales#generate_boletos', as: :generate_boletos
        delete '/destroy_boletos' => 'sales#destroy_boletos', as: :destroy_boletos
      end
      resources :boletos, except: %w(index show)
    end
    resources :users do
      collection do
        get '/perfil' => 'users#profile', as: :profile
        patch 'update_password'
      end
    end

    devise_scope :user do
      authenticated :user do
        root to: 'dashboard#show', as: :authenticated_root
      end

      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  has_many :orders

  def generate_password
    Devise.friendly_token.first(8)
  end
end

app/controllers/users_controller.rb
class UsersController < AdminController
  before_action :set_user, only: %w[show edit update destroy]

  def index
    @users = User.all.order(:name)
  end

  def show; end

  def edit; end

  def update
    @user.update_attributes(user_params)
    respond_with @user, location: users_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    password = @user.generate_password
    @user.password = password
    if @user.save
      UsersMailer.new_user_mail(@user, password).deliver_now
      flash[:notice] = 'Usuário criado com sucesso!'
      redirect_to users_path
    else
      flash[:alert] = 'Erro ao adicionar usuário!'
      render :new
    end
  end

  def destroy; end

  def profile
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      flash[:notice] = 'Senha alterada com sucesso!'
      redirect_to profile_users_path
    else
      flash[:alert] = 'Erro ao salvar sua senha'
      render 'profile'
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params
      .require(:user)
      .permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
<%= f.input :name %>
<%= f.input :email, required: true %>
<%= f.submit "Salvar Usuário", class: 'btn btn-success' %>
<%= link_to "Cancelar", users_path, class: 'btn btn-default' %>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editar Usuário</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Usuários</h3>
  </div>
  <div class="panel-body">
    <% if @users.empty? %>
    <p>Não há usuários cadastradas</p>
    <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>E-mail</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |u| %>
        <tr>
          <td><%= u.id %></td>
          <td><%= u.name %></td>
          <td><%= u.email %></td>
          <td>
            <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_user_path(u) %>
            <%= link_to "<i class='fa fa-trash'></i>".html_safe, user_path(u), method: :delete, data: {confirm: "Tem certeza que deseja excluir o usuário #{u.name}?"} if u != current_user %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Novo Usuário</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Editar Perfil
  </div>
  <div class="panel-body">
    <h5><strong>Nome:</strong> <%= @user.name %></h5>
    <p>Preencha abaixo para trocar sua senha</p>
    <%= simple_form_for @user, url: update_password_users_path do |f| %>
    <%= f.input :current_password %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.submit "Salvar", class: 'btn btn-default' %>
    <% end %>
  </div>

</div>