config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /pt|en/ do
    devise_for :users

    get 'states/:country' => 'admin#states'
    get 'cities/:country/:state' => 'admin#cities'
    get 'listapedidos' => 'orders#all_orders', :as => :all_orders

    resources :customers do
      patch 'generate_link'
    end
    resources :costs
    resources :orders do
      member do
        patch '/confirm_sale' => 'orders#confirm_sale', as: :confirm_sale
        patch '/reject_sale' => 'orders#reject_sale', as: :reject_sale
      end
    end
    resources :sales, only: %w(index show destroy) do
      member do
        post '/generate_boletos' => 'sales#generate_boletos', as: :generate_boletos
        delete '/destroy_boletos' => 'sales#destroy_boletos', as: :destroy_boletos
      end
      resources :boletos, except: %w(index show)
    end
    resources :users do
      collection do
        get '/perfil' => 'users#profile', as: :profile
        patch 'update_password'
      end
    end

    devise_scope :user do
      authenticated :user do
        root to: 'dashboard#show', as: :authenticated_root
      end

      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :set_status
  belongs_to :customer
  belongs_to :user

  has_many :order_items, dependent: :destroy
  has_many :boletos, dependent: :destroy
  usar_como_dinheiro :total, :hour_price
  enum status: ['Cotação', 'Pedido de venda', 'Declinada']

  accepts_nested_attributes_for :order_items, reject_if: :all_blank, allow_destroy: true

  validates :expiration_date, presence: true
  validates :total, presence: true
  validates :payment_method, presence: true
  validate :hourly_cost_minimum

  scope :quotations, -> { where(status: 'Cotação') }
  scope :sales, -> { where(status: 'Pedido de venda')}
  scope :rejected, -> { where(status: 'Declinada')}
  scope :sales_this_month, -> { where(status: 'Pedido de venda', confirmed_at: Time.now.beginning_of_month..Time.now.end_of_month) }

  def hourly_cost_minimum
    if hour_price < Order.hourly_cost
      errors.add(:hour_price, 'não pode ser menor do que o valor mínimo da hora.')
    end
  end

  def self.hourly_cost
    costs = Cost.sum(:value)
    (costs / 160) * 1.1
  end

  def set_status
    self.status = 0
  end
end

app/controllers/orders_controller.rb
class OrdersController < AdminController
  before_action :set_hourly, only: %w[new create edit update]
  before_action :set_order, only: %w[edit update destroy show confirm_sale reject_sale]

  def new
    @order = Order.new
    @order.hour_price = @hourly
    @order.order_items.build
  end

  def create
    @order = Order.create(order_params)
    respond_with @order, location: orders_path
  end

  def all_orders
    @orders = Order.all
    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"pedidos.csv\""
        headers['Content-Type'] ||= 'text/csv;charset=UTF-8'
      end
      format.xls do
        headers['Content-Disposition'] = "attachment; filename=\"pedidos.xls\""
        headers['Content-Type'] ||= 'text/xls;charset=UTF-8'
      end
    end
  end

  def index
    @orders = Order.quotations.order('id DESC')
    @rejected = Order.rejected.order('id DESC')
  end

  def confirm_sale
    @order.update_attributes(status: 'Pedido de venda', confirmed_at: Time.current)
    respond_with @sale, location: orders_path
  end

  def reject_sale
    @order.update_attributes(status: 'Declinada')
    respond_with @order, location: orders_path
  end

  def edit; end

  def update
    @order.update_attributes(order_params)
    respond_with @order, location: orders_path
  end

  def destroy
    @order.destroy
    respond_with @order, location: orders_path
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "SO#{@order.id} - #{@order.customer.name}",
               template: 'orders/order.html.erb',
               layout: 'layouts/pdf',
               disposition: 'attachment',
               margin: {
                 top: 20,
                 bottom: 20
               },
               show_as_html: params.key?('debug'),
               header: {
                 html: { template: 'layouts/pdf_header.html.erb' },
                 spacing: 0
               },
               footer: {
                 html: { template: 'layouts/pdf_footer.html.erb' },
                 spacing: 0
               }
      end
    end
  end

  private

  def order_params
    params
      .require(:order)
      .permit(:hour_price, :dollar, :user_id, :customer_id, :expiration_date, :observations, :tax, :total, :payment_method, :show_item_price, :discount, order_items_attributes: %i[id name description hours quantity value _destroy])
  end

  def set_order
    @order = Order.includes(:customer).find_by(id: params[:id])
    if @order.status == "Pedido de venda"
      flash[:alert] = "Essa SO já virou uma venda!"
      redirect_to orders_path
    end
  end

  def set_hourly
    @hourly = Order.hourly_cost
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for @order do |f| %>
<span data-dollar="<%= @order.dollar %>" id="dollar"></span>
<%= f.association :customer %>
<%= f.association :user, selected: (@order.user.present?)? @order.user.id : current_user.id  %>
<%= f.input :expiration_date %>
<%= f.input :dollar, label: 'Dólar?' %>
<span id="hour-price" data-hour-price="<%= (@hourly).round(2) %>">Valor mínimo da hora: <%= number_to_currency @hourly %></span>
<%= f.input :hour_price, input_html: {id: 'hour-price1', class: "money", style: "width: 200px", value: @order.hour_price.quantia}, as: :string %>
<h4>Itens</h4>
<div class="items">
<%= f.simple_fields_for :order_items do |item| %>
<%= render 'order_item_fields', f: item %>
<% end %>
<div class="links">
<%= link_to_add_association 'Adicionar Item', f, :order_items, style: "display: block" %>
<%= f.input :tax, label: 'Incluir imposto no orçamento? (ISS 9%)' %>
<%= f.input :show_item_price, label: 'Exibir o valor de cada item?' %>
<%= f.input :discount, collection: 0..20, include_blank: false, label: "Desconto (%)" %>
<%= f.input :total, as: :string, input_html:{ readonly: true, id: "total-order", style: "width: 200px"} %>
</div>
</div>
<%= f.input :observations %>
<%= f.input :payment_method, collection: (1..12).map {|p| ["#{p}x",p]} %>
<%= f.submit "Salvar Pedido", class: 'btn btn-success' %>
<%= link_to "Cancelar", orders_path, class: 'btn btn-default' %>
<% end %>

app/views/orders/_order_item_fields.html.erb
<div class="order-item form-inline nested-fields" id="container">
  <%= f.input :name, label: false, placeholder: 'Nome' %>
  <%= f.input :description, label: false, placeholder: 'Descrição', input_html: {rows: 1, cols: 30} %>
  <%= f.input :quantity, label: false, placeholder: 'Qtd', input_html: {style:"width: 100px"} %>
  <%= f.input :hours, label: false, placeholder: 'Horas', input_html: {style:"width: 100px", class: 'item-hours'} %>
  <%= f.input :value, as: :string, label: false, placeholder: 'Valor', input_html: {style:"width: 150px", class: 'money item-price', readonly: true} %>
  <%= hidden_field_tag :value_hidden, nil, class: 'hidden_value' %>
  <%= link_to_remove_association "Remover Item", f %>
</div>

app/views/orders/_quotations.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Cotações</h3>
  </div>
  <div class="panel-body">
    <% if @orders.empty? %>
    <p>Não há cotações cadastradas</p>
    <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Cliente</th>
          <th>Total</th>
          <th>Data</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |o| %>
        <tr>
          <td><%= "SO#{o.id}" %></td>
          <td><%= o.customer.name %></td>
          <td><%= (o.dollar)? number_to_currency(o.total, unit: "US$") : number_to_currency(o.total) %></td>
          <td><%= l o.created_at, format: :short %></td>
          <td>
            <%= link_to "<i class='fa fa-eye'></i>".html_safe, order_path(o) %>
            <%= link_to "<i class='fa fa-download'></i>".html_safe, order_path(o, format: 'pdf'), target: '_blank' %>
            <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_order_path(o) %>
            <%= link_to "<i class='fa fa-trash'></i>".html_safe, order_path(o), method: :delete, data: {confirm: "Tem certeza que deseja excluir a cotação SO#{o.id}?"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/orders/_rejected_quotations.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Cotações Rejeitadas</h3>
  </div>
  <div class="panel-body">
    <% if @rejected.empty? %>
    <p>Não há cotações rejeitadas</p>
    <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Cliente</th>
          <th>Total</th>
          <th>Data</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @rejected.each do |o| %>
        <tr>
          <td><%= "SO#{o.id}" %></td>
          <td><%= o.customer.name %></td>
          <td><%= (o.dollar)? number_to_currency(o.total, unit: "US$") : number_to_currency(o.total) %></td>
          <td><%= l o.created_at, format: :short %></td>
          <td>
            <%= link_to "<i class='fa fa-eye'></i>".html_safe, order_path(o) %>
            <%= link_to "<i class='fa fa-download'></i>".html_safe, order_path(o, format: 'pdf'), target: '_blank' %>
            <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_order_path(o) %>
            <%= link_to "<i class='fa fa-trash'></i>".html_safe, order_path(o), method: :delete, data: {confirm: "Tem certeza que deseja excluir a cotação SO#{o.id}?"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/orders/all_orders.xls.erb
<?xml version="1.0" encoding="utf-8" ?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Empréstimos">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Cliente</Data></Cell>
        <Cell><Data ss:Type="String">Vendedor</Data></Cell>
        <Cell><Data ss:Type="String">Data</Data></Cell>
        <Cell><Data ss:Type="String">Valor</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
      </Row>
    <% @orders.each do |order| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= order.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= order.customer.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= order.user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= order.created_at.strftime('%d/%m/%Y') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= (order.dollar)? number_to_currency(order.total, unit: "US$") : number_to_currency(order.total) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= order.status %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/orders/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editar Cotação</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/index.html.erb
<%= render 'quotations' %>
<%= render 'rejected_quotations' %>

app/views/orders/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Nova Cotação</h3>
  </div>
  <div class="panel-body" data-turbolinks="false">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/order.html.erb
<div class="casa-headings">
  <span><strong>CASA</strong>DE<strong>28</strong></span>
  <p>Razão Social: Figura de Linguagem Comunicação LTDA</p>
  <p>CNPJ: 20.700.998/0001-44</p>
  <p>R. França Pinto, 926, Vila Mariana - São Paulo - SP - 04016-004</p>
  <p>(11) 3522-4440 - fale@casade28.com.br</p>
</div>
<div class="customer-headings">
  <span><strong>Cliente:</strong></span>
  <p><%= @order.customer.name %></p>
  <% if @order.customer.razao_social.present? && @order.customer.pj == "Pessoa Jurídica" %>
  <p>Razão Social: <%= @order.customer.razao_social %></p>
  <% end %>
  <% if @order.customer.cnpj.present? && @order.customer.pj == "Pessoa Jurídica" %>
  <p>CNPJ: <%= @order.customer.cnpj %></p>
  <% end %>
  <% if @order.customer.cpf.present? && @order.customer.pj == "Pessoa Física" %>
  <p>CPF: <%= @order.customer.cpf %></p>
  <% end %>
  <% if @order.customer.address.present? %>
  <p><%= "#{@order.customer.address} - #{@order.customer.city} - #{@order.customer.state} - #{@order.customer.zip_code}" %></p>
  <% end %>
  <p><% if @order.customer.phone.present? %>(11) 3522-4440 <% end %><% if @order.customer.email.present? %> - fale@casade28.com.br<% end %></p>
</div>
<div class="order">
  <h2>Proposta <span class="order-no">#SO<%= @order.id %></span></h2>
  <table class="order-info">
    <thead>
      <tr>
        <td>Data da Proposta</td>
        <td>Proposta valida até</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= l @order.created_at, format: :date %></td>
        <td><%= l @order.expiration_date, format: :default %></td>
      </tr>
    </tbody>
  </table>
  <table class="order-items">
    <thead>
      <tr>
        <th width="23%">Nome</th>
        <th width="65%">Descrição</th>
        <th width="2%" style="padding-left: 5px;">Quantidade</th>
        <% if @order.show_item_price %>
        <th width="10%">Valor</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @order.order_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= simple_format item.description %></td>
        <td style="padding-left: 5px;"><%= item.quantity %></td>
        <% if @order.show_item_price %>
        <td>
          <% if @order.dollar %>
          <%= (@order.tax)? number_to_currency(item.value*1.09, unit: "US$") : number_to_currency(item.value, unit: "US$") %>
          <% else %>
          <%= (@order.tax)? (number_to_currency (item.value*1.09)) : (number_to_currency (item.value)) %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
      <tr >
        <td colspan="1"></td>
        <td colspan="3" class="order-total">
          <% if @order.discount > 0 %><p>Desconto: <%= @order.discount %>%</p><% end %>
          <p><strong>Total: <%= (@order.dollar)? number_to_currency(@order.total, unit: "US$") : number_to_currency(@order.total) %></strong></p>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="observations">
    <span class="title">Observações</span>
    <%= simple_format @order.observations %>
  </div>
  <div class="payment_method">
    <span class="title">Forma de pagamento</span>
    <span class="payment"><%= "#{@order.payment_method}x de  #{(@order.dollar)? number_to_currency(@order.total/@order.payment_method, unit: "US$") : number_to_currency(@order.total/@order.payment_method)} - Boleto Bancário" %></span>
  </div>
  <div class="signatures">
    <div class="signature">
      <span><%= @order.customer.name %></span>
    </div>

    <div class="signature">
      <span><strong>CASA</strong>DE<strong>28</strong></span>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">SO<%= @order.id %> - <%= @order.customer.name %></h3>
  </div>
  <div class="panel-body">
    <div class="order">
      <h2>Proposta <span class="order-no">#SO<%= @order.id %></span></h2>
      <table class="order-info">
        <thead>
          <tr>
            <td>Data da Proposta</td>
            <td>Proposta valida até</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= l @order.created_at, format: :date %></td>
            <td><%= l @order.expiration_date, format: :default %></td>
          </tr>
        </tbody>
      </table>
      <table class="order-items">
        <thead>
          <tr>
            <th width="23%">Nome</th>
            <th width="65%">Descrição</th>
            <th width="2%" style="padding-left: 5px;">Quantidade</th>
            <th width="10%">Valor</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.each do |item| %>
          <tr>
            <td><%= item.name %></td>
            <td><%= simple_format item.description %></td>
            <td style="padding-left: 5px;"><%= item.quantity %></td>
            <td>
              <% if @order.dollar %>
              <%= (@order.tax)? number_to_currency(item.value*1.09, unit: "US$") : number_to_currency(item.value, unit: "US$") %>
              <% else %>
              <%= (@order.tax)? (number_to_currency (item.value*1.09)) : (number_to_currency (item.value)) %>
              <% end %>
            </td>
          </tr>
          <% end %>
          <tr >
            <td colspan="1"></td>
            <td colspan="3" class="order-total">
              <% if @order.discount > 0 %><p>Desconto: <%= @order.discount %>%</p><% end %>
              <p><strong>Total: <%= (@order.dollar)? number_to_currency(@order.total, unit: "US$") : number_to_currency(@order.total) %></strong></p>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="observations">
        <span class="title">Observações</span>
        <%= simple_format @order.observations %>
      </div>
      <div class="payment_method">
        <span class="title">Forma de pagamento</span>
        <span class="payment"><%= "#{@order.payment_method}x de #{ (@order.dollar)? number_to_currency(@order.total/@order.payment_method, unit: "US$") : number_to_currency(@order.total/@order.payment_method)} - Boleto Bancário" %></span>
      </div>
    </div>
    <%= link_to "<i class='fa fa-check'></i> Confirmar venda".html_safe, confirm_sale_order_path(@order), method: :patch, class: 'btn btn-success', data: {confirm: "Tem certeza que deseja confirmar a venda SO#{@order.id}?"} %>
    <%= link_to "<i class='fa fa-thumbs-down'></i> Rejeitar venda".html_safe, reject_sale_order_path(@order), method: :patch, class: 'btn btn-warning', data: {confirm: "Tem certeza que deseja recusar a proposta SO#{@order.id}?"} if @order.status != "Declinada" %>
    <%= link_to "<i class='fa fa-download'></i> Download".html_safe, order_path(@order, format: 'pdf'), class: 'btn btn-default' %>
    <%= link_to "<i class='fa fa-trash'></i> Excluir".html_safe, order_path(@order), method: :delete, class: 'btn btn-danger', data: {confirm: "Tem certeza que deseja excluir a cotação SO#{@order.id}?"} %>
    <%= link_to "<i class='fa fa-edit'></i> Editar".html_safe, edit_order_path(@order), class: 'btn btn-default' %>
    <%= link_to "<i class='fa fa-arrow-left'></i> Voltar".html_safe, orders_path, class: 'btn btn-default' %>
  </div>
</div>