config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /pt|en/ do
    devise_for :users

    get 'states/:country' => 'admin#states'
    get 'cities/:country/:state' => 'admin#cities'
    get 'listapedidos' => 'orders#all_orders', :as => :all_orders

    resources :customers do
      patch 'generate_link'
    end
    resources :costs
    resources :orders do
      member do
        patch '/confirm_sale' => 'orders#confirm_sale', as: :confirm_sale
        patch '/reject_sale' => 'orders#reject_sale', as: :reject_sale
      end
    end
    resources :sales, only: %w(index show destroy) do
      member do
        post '/generate_boletos' => 'sales#generate_boletos', as: :generate_boletos
        delete '/destroy_boletos' => 'sales#destroy_boletos', as: :destroy_boletos
      end
      resources :boletos, except: %w(index show)
    end
    resources :users do
      collection do
        get '/perfil' => 'users#profile', as: :profile
        patch 'update_password'
      end
    end

    devise_scope :user do
      authenticated :user do
        root to: 'dashboard#show', as: :authenticated_root
      end

      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %w(show destroy generate_boletos destroy_boletos)

  def index
    @orders = Order.sales.order('id DESC')
  end

  def show
  end

  def destroy
    @order.destroy
    respond_with @order, location: orders_path
  end

  def generate_boletos
    if @order.payment_method.nil? || @order.status != 'Pedido de venda'
      redirect_to order_path(@order)
    end
    if params[:date].blank?
      flash[:alert] = 'Favor preencher a data do primeiro boleto'
      render 'sales/show'
      return
    end
    date = Date.parse(params[:date])
    value = @order.total/@order.payment_method
    for i in 0..(@order.payment_method-1)
      @boleto = @order.boletos.build
      @boleto.due_date = date + i.months
      @boleto.value = value
      @boleto.save
    end
    flash[:notice] = "Boletos criados com sucesso!"
    redirect_to sale_path(@order)
  end

  def destroy_boletos
    if @order.boletos.destroy_all
      flash[:notice] = "Boletos apagado com sucesso!"
    else
      flash[:alert] = "Erro ao apagar os boletos!"
    end
    redirect_to sale_path(@order)
  end

  private

  def set_sale
    @order = Order.find_by(id: params[:id])
    if @order.status != "Pedido de venda"
      flash[:alert] = "Ação apenas disponível para pedidos de venda!"
      redirect_to sales_path
    end
  end

end

app/views/sales/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Vendas</h3>
  </div>
  <div class="panel-body">
    <% if @orders.empty? %>
    <p>Não há vendas</p>
    <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Cliente</th>
          <th>Total</th>
          <th>Data</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |o| %>
        <tr>
          <td><%= "SO#{o.id}" %></td>
          <td><%= o.customer.name %></td>
          <td><%= number_to_currency o.total %></td>
          <td><%= l o.confirmed_at, format: :short %></td>
          <td>
            <%= link_to "<i class='fa fa-eye'></i>".html_safe, sale_path(o) %>
            <%= link_to "<i class='fa fa-trash'></i>".html_safe, sale_path(o), method: :delete, data: {confirm: "Tem certeza que deseja excluir a venda SO#{o.id}?"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/sales/show.html.erb
<!-- Modal Gerar Boletos -->
<div class="modal fade" id="generateBoletoModal" tabindex="-1" role="dialog" aria-labelledby="generateBoletoModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="generateBoletoModal">Gerar Boletos - SO<%= @order.id %></h4>
      </div>
      <div class="modal-body">
        Essa ação irá gerar <%= "#{@order.payment_method} boletos de #{number_to_currency (@order.total/@order.payment_method)}" %>
        <%= form_tag generate_boletos_sale_path(@order), method: :post do |f| %>
        <label for="data">
          Data do primeiro boleto
          <%= date_field_tag :date %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <%= submit_tag "Gerar", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal Editar Boleto -->
  <div class="modal fade" id="boletoModal" tabindex="-1" role="dialog" aria-labelledby="boletoModal">

  </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">SO<%= @order.id %> - <%= @order.customer.name %></h3>
    </div>
    <div class="panel-body">
      <div class="order">
        <h2>Venda <span class="order-no">#SO<%= @order.id %></span></h2>
        <table class="order-info">
          <thead>
            <tr>
              <td>Data da venda</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= l @order.confirmed_at, format: :date %></td>
            </tr>
          </tbody>
          <dl>
            <dt>Vendedor</dt>
            <dd><%= @order.user.name %></dd>
          </dl>
        </table>
        <table class="order-items">
          <thead>
            <tr>
              <th width="25%">Nome</th>
              <th width="63%">Descrição</th>
              <th width="2%">Quantidade</th>
              <th width="10%" style="text-align: right;">Valor</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_items.each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <td><%= simple_format item.description %></td>
              <td style="text-align: right;"><%= item.quantity %></td>
              <td style="text-align: right;">
                <% if @order.dollar %>
                <%= (@order.tax)? number_to_currency(item.value*1.09, unit: "US$") : number_to_currency(item.value, unit: "US$") %>
                <% else %>
                <%= (@order.tax)? (number_to_currency (item.value*1.09)) : (number_to_currency (item.value)) %>
                <% end %>
              </td>
            </tr>
            <% end %>
            <tr >
              <td colspan="1"></td>
              <td colspan="3" class="order-total">
                <% if @order.discount > 0 %><p>Desconto: <%= @order.discount %>%</p><% end %>
                <p><strong>Total: <%= (@order.dollar)? number_to_currency(@order.total, unit: "US$") : number_to_currency(@order.total) %></strong></p>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="observations">
          <span class="title"><strong>Observações</strong></span>
          <%= simple_format @order.observations %>
        </div>
        <div class="payment_method">
          <span class="title">Forma de pagamento</span>
          <span class="payment"><%= "#{@order.payment_method}x de #{ (@order.dollar)? number_to_currency(@order.total/@order.payment_method, unit: "US$") : number_to_currency(@order.total/@order.payment_method)} - Boleto Bancário" %></span>
        </div>
        <div class="boletos">
          <% if @order.boletos.any? %>
          <span>Boletos</span>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Parcela</th>
                <th>Valor</th>
                <th>Data de Vencimento</th>
                <th>Data do Pagamento</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @order.boletos.order("due_date").each_with_index do |b,i| %>
              <tr class="<%= 'vencido' if b.due_date < Date.today && b.payment_date == nil%><%= 'pago' if b.payment_date.present? %>" data-toggle="tooltip" data-placement="top" title="<%= 'Vencido' if b.due_date < Date.today %>">
                <td><%= i+1 %></td>
                <td><%= number_to_currency(b.value) %></td>
                <td><%= l b.due_date, format: :default %></td>
                <td><%= l b.try(:payment_date), format: :default if b.payment_date.present? %></td>
                <td>
                  <%= link_to "<i class='fa fa-trash'></i>".html_safe, sale_boleto_path(@order,b), method: :delete, data: {confirm: "Tem certeza que deseja excluir esse boleto?"} %>
                  <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_sale_boleto_path(@order,b), remote: true %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% end %>
      </div>
      <%= link_to "<i class='fa fa-trash'></i> Excluir".html_safe, sale_path(@order), method: :delete, class: 'btn btn-danger', data: {confirm: "Tem certeza que deseja excluir a venda SO#{@order.id}?"} %>
      <%= link_to "<i class='fa fa-arrow-left'></i> Voltar".html_safe, sales_path, class: 'btn btn-default' %>
      <%= link_to "<i class='fa fa-download'></i> Download".html_safe, order_path(@order, format: 'pdf'), target: '_blank', class: 'btn btn-default' %>
      <% if @order.boletos.empty? %>
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#generateBoletoModal">
        <i class='fa fa-barcode'></i> Gerar Boletos
      </button>
      <% else %>
      <%= link_to "<i class='fa fa-barcode'></i> Apagar Boletos".html_safe, destroy_boletos_sale_path(@order), class: 'btn btn-danger', method: :delete, data: {confirm: "Tem certeza que deseja apagar todos os boletos gerados?"} %>
      <%= link_to "<i class='fa fa-barcode'></i> Criar Boleto".html_safe, new_sale_boleto_path(@order), class: 'btn btn-success', remote: true %>
      <% end %>
    </div>
  </div>