config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /pt|en/ do
    devise_for :users

    get 'states/:country' => 'admin#states'
    get 'cities/:country/:state' => 'admin#cities'
    get 'listapedidos' => 'orders#all_orders', :as => :all_orders

    resources :customers do
      patch 'generate_link'
    end
    resources :costs
    resources :orders do
      member do
        patch '/confirm_sale' => 'orders#confirm_sale', as: :confirm_sale
        patch '/reject_sale' => 'orders#reject_sale', as: :reject_sale
      end
    end
    resources :sales, only: %w(index show destroy) do
      member do
        post '/generate_boletos' => 'sales#generate_boletos', as: :generate_boletos
        delete '/destroy_boletos' => 'sales#destroy_boletos', as: :destroy_boletos
      end
      resources :boletos, except: %w(index show)
    end
    resources :users do
      collection do
        get '/perfil' => 'users#profile', as: :profile
        patch 'update_password'
      end
    end

    devise_scope :user do
      authenticated :user do
        root to: 'dashboard#show', as: :authenticated_root
      end

      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= authenticated_root_path if user_signed_in? %>">
        <%= image_tag("logo-casa.png") %>
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><a href="<%= authenticated_root_path %>">Dashboard</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clientes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= customers_path %>">Lista</a></li>
            <li><a href="<%= new_customer_path %>">Novo</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Custos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= costs_path %>">Lista</a></li>
            <li><a href="<%= new_cost_path %>">Novo</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cotações <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= orders_path %>">Lista</a></li>
            <li><a href="<%= new_order_path %>">Novo</a></li>
            <li><%= link_to "Relatório", all_orders_path(format: 'xls') %></li>
          </ul>
        </li>
        <li><a href="<%= sales_path %>">Vendas</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Usuários <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= users_path %>">Lista</a></li>
            <li><a href="<%= new_user_path %>">Novo</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= profile_users_path %>">Perfil</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

      </ul>
      <% end %>
      <% if !user_signed_in? %>
      <ul class="nav navbar-nav navbar-right countries">
        <li><%= link_to flag_icon(:br), locale: nil %></a></li>
        <li><%= link_to flag_icon(:us), locale: :en %></a></li>
      </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name=viewport content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <title>CASA de 28 - Sistema</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= custom_bootstrap_flash %>
  <%= render 'layouts/navigation' if user_signed_in? || controller_name == "customers" %>
  <% if user_signed_in? || controller_name == "customers" %>
  <div class="container">
    <%= yield %>
  </div>
  <% else %>
  <%= yield %>
  <% end %>
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700" rel="stylesheet">
    <%= wicked_pdf_stylesheet_link_tag    'pdf' %>
    <title></title>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf_footer.html.erb
<div class="footer-pdf">
  <div class="row">
    <div class="col-xs-5 left">
      (11) 3522-4440 - fale@casade28.com.br
    </div>
    <div class="col-xs-2 center">
      www.<span><strong>CASA</strong>DE<strong>28</strong></span>.com.br
    </div>
    <div class="col-xs-5 right">
      Rua França Pinto, 926 - Vl. Mariana - São Paulo - SP - 04016-004
    </div>
  </div>
</div>

app/views/layouts/pdf_header.html.erb
<div class="header-pdf">
  <%= wicked_pdf_image_tag "logo-casa.png" %>
</div>